name: torch-stress
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - pytorch=1.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.3
  - pip
  - pip:
    - nvidia-ml-py==11.515.75
    - uriwd==2.1.2
